{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8cd5bd6f-4c2f-45c6-b35d-609907756999",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-04-05 11:52:02.620 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-04-05 11:52:02.624 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:02.626 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.376 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-04-05 11:52:03.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.379 No runtime found, using MemoryCacheStorageManager\n",
      "2025-04-05 11:52:03.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.892 Thread 'Thread-5': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.894 Thread 'Thread-5': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:03.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:04.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.235 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-04-05 11:52:05.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# === Load Data ===\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    excel_path = r\"C:\\Users\\user\\Desktop\\personal\\DE_Assesment\\DE_Assesment_Results.xlsx\"\n",
    "    df_combined = pd.read_excel(excel_path, sheet_name=\"task3_summary_report\")\n",
    "    return df_combined\n",
    "\n",
    "# === Streamlit Layout ===\n",
    "st.set_page_config(page_title=\"Token Analytics Dashboard\", layout=\"wide\")\n",
    "st.title(\"📊 Token Distribution Dashboard - Task 3\")\n",
    "\n",
    "# === Load and Display Table ===\n",
    "df = load_data()\n",
    "st.subheader(\"📦 Summary Table: Token Holdings, Sent, Received\")\n",
    "st.dataframe(df.style.format({\n",
    "    \"Token Holding\": \"{:.6f}\",\n",
    "    \"% of Total Holding\": \"{:.2f}%\",\n",
    "    \"Tokens Sent\": \"{:.6f}\",\n",
    "    \"% of Total Sent\": \"{:.2f}%\",\n",
    "    \"Tokens Received\": \"{:.6f}\",\n",
    "    \"% of Total Received\": \"{:.2f}%\"\n",
    "}))\n",
    "\n",
    "# === Visualizations ===\n",
    "st.subheader(\"📈 Top Contributors - Visual Insights\")\n",
    "\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "with col1:\n",
    "    st.markdown(\"#### 🪙 Token Holdings\")\n",
    "    fig1, ax1 = plt.subplots(figsize=(5, 4))\n",
    "    ax1.barh(df['address'], df['Token Holding'], color='green')\n",
    "    ax1.set_xlabel(\"Token Holding\")\n",
    "    ax1.invert_yaxis()\n",
    "    st.pyplot(fig1)\n",
    "\n",
    "with col2:\n",
    "    st.markdown(\"#### 📤 Tokens Sent\")\n",
    "    fig2, ax2 = plt.subplots(figsize=(5, 4))\n",
    "    ax2.barh(df['address'], df['Tokens Sent'], color='red')\n",
    "    ax2.set_xlabel(\"Tokens Sent\")\n",
    "    ax2.invert_yaxis()\n",
    "    st.pyplot(fig2)\n",
    "\n",
    "with col3:\n",
    "    st.markdown(\"#### 📥 Tokens Received\")\n",
    "    fig3, ax3 = plt.subplots(figsize=(5, 4))\n",
    "    ax3.barh(df['address'], df['Tokens Received'], color='blue')\n",
    "    ax3.set_xlabel(\"Tokens Received\")\n",
    "    ax3.invert_yaxis()\n",
    "    st.pyplot(fig3)\n",
    "\n",
    "# === Footer ===\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"Built with ❤️ using Streamlit\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9f196d6b-f501-4f31-b3c8-33e4b0c2c38d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
